apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-agekey-secret
  interval: 10m0s
  path: ./clusters/k3s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system