---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      version: 0.16.0-rc.4
  install:
    crds: Create
  interval: 5m0s
  upgrade:
    crds: CreateReplace
  values:
    branchPlanner:
      enabled: false
      image:
        tag: v0.16.0-rc.4
