apiVersion: v1
data:
    token: ENC[AES256_GCM,data:96nZswott9ho3RG32pkHD8wl+gz4H6SomCydLpZ6mjok582RdtZhr69u7torV6VIh627GDHdu6Rz0rwmUMwJQeHJf/HZ+H3V0Dh7cMGyCJzRRgpIohYRoMAIERbwZJiY/BZ9fgJN/OnSDmmralmjiUjmbTaU+yqPsEV0M5CTS9SxovWhbawZ6YwjQJqmS+FvTiZnTbqL3moh9fBR/AiKDl+d4ul3pngxsrG4WR1m06/qFq7uooQIUvPWeZAVim/UaDwhJpl3/eP8UMZuDWPXqvoi3eyIhnGxbLe+W9ffD2bIU0wMlYBmfZdPoZHEtKj8+HgrVQGcGxa1HY1OsmTAWZ99seSokmvGYncf3aadKFrXsiDuzivBjAYAIue6gQrAmBl8Qao7F6ZLaZJJ,iv:rAATKFqYwnRPItjUkhMWHH7KXce8Cw9eZutpcw8WSH0=,tag:YtsJNf8MjVaRVB9gLkVTCg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gcp-auth-secret
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmkct3th5cpmsapg58uwghv6wm8kue3x70k5wyhxh478uttylsmqtn6qtk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSTZ3Lzltclk3OEtwaWli
            REswVnhhMDhWUXdNZ0RORy9kWmM1bGQwRFIwCnAwbTF3RkJBcTFocTM3UDVtbjJK
            RC9DQ09YeHFHZDVTazZiM1ZMQ2kwMDgKLS0tIDRUWlMwbmwwM1c0dGZjQ2dHeTMy
            dTR2TkFwc0VWbkh6djdJd1U1ME9lbGsKvD/8DecFGVJ/AEpOL5GTLqpN+As1NRLx
            Phb4NU9N1FTLr9uUSdmI/mh0ZV75bvnEM9sEITvwOfrX5HDpAFwXaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T17:07:20Z"
    mac: ENC[AES256_GCM,data:uHzXaogqW8M9LnWDzLVim7/Ya2Y+2Ky1XKftxjhQnrADL7Ps95X4jwPqKD1HQWqfhDOPogTp3CsWpWQmWYs/wdVdlkSpxvVQxiAZ7P0g6J+P37EscY4DgmiOOKXtQHCfoFLj8mz/xIT5IbqV8SHl/7GfnbrIv5Z1SsfBs+L8A0E=,iv:V5kpOp4CDmLbDoH2m3zGQg8C7gHUTTu2MfZEj/uktTI=,tag:He2MO4XQvcbOqQPZXEy9Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
